-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 19:57:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nama` VARCHAR(45) NOT NULL,
  `saldo` VARCHAR(45) NOT NULL,
  `role` ENUM('Konsumen', 'Admin') NOT NULL,
  `is_enable` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produk` (
  `id` INT NOT NULL,
  `nama` VARCHAR(255) NOT NULL,
  `deskripsi` TEXT NOT NULL,
  `harga` DOUBLE NOT NULL,
  `stock` INT NOT NULL,
  `photo_path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaksi` (
  `id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `total` DOUBLE NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_transactions_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detail_transaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detail_transaksi` (
  `transaksi_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `harga` DOUBLE NOT NULL,
  PRIMARY KEY (`transaksi_id`, `products_id`),
  INDEX `fk_transactions_has_products_products1_idx` (`products_id` ASC),
  INDEX `fk_transactions_has_products_transactions1_idx` (`transaksi_id` ASC),
  CONSTRAINT `fk_transactions_has_products_transactions1`
    FOREIGN KEY (`transaksi_id`)
    REFERENCES `mydb`.`transaksi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `mydb`.`produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`history_saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`history_saldo` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  `nominal` DOUBLE NOT NULL,
  `jenis` ENUM('Topup', 'Beli') NOT NULL,
  `transactions_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_history_saldo_users1_idx` (`users_id` ASC),
  INDEX `fk_history_saldo_transactions1_idx` (`transactions_id` ASC),
  CONSTRAINT `fk_history_saldo_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_history_saldo_transactions1`
    FOREIGN KEY (`transactions_id`)
    REFERENCES `mydb`.`transaksi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`keranjang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`keranjang` (
  `users_id` INT NOT NULL,
  `produk_id` INT NOT NULL,
  `jumlah` INT NOT NULL,
  PRIMARY KEY (`users_id`, `produk_id`),
  INDEX `fk_users_has_products_products1_idx` (`produk_id` ASC),
  INDEX `fk_users_has_products_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_products_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_products_products1`
    FOREIGN KEY (`produk_id`)
    REFERENCES `mydb`.`produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chats` (
  `id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `pesan` TEXT NOT NULL,
  `pengirim` INT NOT NULL,
  `Penerima` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Chats_users1_idx` (`pengirim` ASC),
  INDEX `fk_Chats_users2_idx` (`Penerima` ASC),
  CONSTRAINT `fk_Chats_users1`
    FOREIGN KEY (`pengirim`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chats_users2`
    FOREIGN KEY (`Penerima`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login_log` (
  `users_id` INT NOT NULL,
  `date` BLOB NOT NULL,
  `status` TINYINT NOT NULL,
  INDEX `fk_table1_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_table1_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
